import java.util.HashSet;
import java.util.Set;

/**
 * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 *
 * @author Nancy Tao
 * @version 12/17/2015
 */
public class Problem29 {

    public static void main(String[] args) {
        Set<Double> powers = new HashSet<>();
        for (int a = 2; a <= 100; a++) {
            for (int b = 2; b <= 100; b++) {
                powers.add(Math.pow(a, b));
            }
        }

        System.out.print(powers.size());
    }
}